### PR TITLE
TriggerEvent modules for EVR Timing

### PR DESCRIPTION
**Pull request by bengineerd**
This PR adds LCLS-I timing support to `TriggerEventBuffer` and `TriggerEventManager`.

Most all of the work is done by `lcls_timing_core.EvrCoreTriggers`, which provides a programmable decode interface for multiple triggers.

Two new generics have been added (`EN_LCLS_I_TIMING_G` and `EN_LCLS_II_TIMING_G`) to allow unneeded logic to optimize out.

`XpmMiniWrapper` now has `TpgMiniStream` so that LCLS-I EVR streams can be generated.

### CODE REVIEW

**Comment by bengineerd** [comment]
Thanks Matt.

Next question is, how do we test this thing? Is there an EVG module I can simulate? A KCU1500 and camera hooked up to an EVR somewhere that we can load the image onto?

**Comment by thatweaver** [comment]
Hi  Ben,

The lcls-timing-core/LCLS-II/core/rtl/TPGMiniCore module has two sets of txData,txDataK outputs and contains a TPGMiniStream module which simulates LCLS-I timing on the first pair.

-Matt

________________________________

**Comment by bengineerd** [comment]
@thatweaver 

I ended up changing the entire structure so that TriggerEventBuffer and TriggerEventManager have the logic for both LCLS-I and LCLS-II. There are generics to allow unused logic to optimize out of only one is needed, but in theory it could also switch dynamically between the two.

Take a look and let me know if you agree with the approach. I suppose we will want to include some kind of flag in the EventHeader struct to indicate EVR or XPM.

**Comment by bengineerd** [comment]
This was not ready to merge.

**Pull request merged**
